export const STYLE_OWNER = 'dsh-manage-sessions:react-slot'

export const CSS = `
.dsm-overlay{position:fixed;inset:0;z-index:1400;display:grid;place-items:center;padding:16px;pointer-events:auto;color:var(--dsw-alias-label-primary,#17181a);font-family:var(--dsw-font-family,Inter,system-ui,sans-serif);box-sizing:border-box}
.dsm-overlay *{box-sizing:border-box}.dsm-mask{position:absolute;inset:0;background:var(--dsw-alias-bg-mask-1,rgba(8,10,14,.54));backdrop-filter:blur(5px)}
.dsm-window,.dsm-confirm{position:relative;display:flex;flex-direction:column;width:min(1080px,calc(100vw - 32px));height:min(760px,calc(100vh - 32px));overflow:hidden;background:var(--dsw-alias-bg-base,#fff);border:1px solid var(--dsw-alias-border-l2,rgba(0,0,0,.14));border-radius:16px;box-shadow:0 28px 90px rgba(0,0,0,.26)}
.dsm-confirm{width:min(500px,calc(100vw - 32px));height:auto;max-height:min(680px,calc(100vh - 32px));padding:22px;gap:16px}
.dsm-head{display:flex;align-items:center;gap:12px;min-height:68px;padding:0 18px;border-bottom:1px solid var(--dsw-alias-border-l2,rgba(0,0,0,.1))}.dsm-head-mark{display:grid;place-items:center;width:36px;height:36px;flex:none;border-radius:10px;color:var(--dsw-alias-brand-primary,#4d6bfe);background:color-mix(in srgb,var(--dsw-alias-brand-primary,#4d6bfe) 10%,transparent)}.dsm-head-copy{min-width:0;flex:1}.dsm-title{margin:0;font-size:18px;line-height:25px;font-weight:680;letter-spacing:-.015em}.dsm-subtitle{margin:1px 0 0;color:var(--dsw-alias-label-tertiary,#73777f);font-size:12px;line-height:18px}
.dsm-icon-btn{width:40px;height:40px;display:grid;place-items:center;flex:none;border:0;border-radius:10px;background:transparent;color:var(--dsw-alias-label-secondary,#565a61);cursor:pointer}.dsm-icon-btn:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover,rgba(0,0,0,.06))}.dsm-icon-btn:disabled{opacity:.42;cursor:not-allowed}
.dsm-icon-btn:focus-visible,.dsm-tab:focus-visible,.dsm-group-toggle:focus-visible,.dsm-row:focus-visible,.dsm-check:focus-visible{outline:2px solid var(--dsw-alias-brand-primary,#4d6bfe);outline-offset:2px}
.dsm-tabs{display:flex;align-items:flex-end;gap:22px;min-height:44px;padding:0 20px;border-bottom:1px solid var(--dsw-alias-border-l2,rgba(0,0,0,.1))}.dsm-tab{position:relative;display:flex;align-items:center;gap:7px;height:44px;border:0;background:transparent;color:var(--dsw-alias-label-secondary,#565a61);font:inherit;font-size:13px;font-weight:620;padding:0 2px;cursor:pointer}.dsm-tab:after{content:"";position:absolute;left:0;right:0;bottom:-1px;height:2px;border-radius:2px;background:transparent}.dsm-tab b{display:inline-grid;place-items:center;min-width:22px;height:20px;padding:0 6px;border-radius:8px;background:var(--dsw-alias-bg-layer-1,rgba(0,0,0,.05));color:var(--dsw-alias-label-tertiary,#73777f);font-size:11px;font-weight:650;font-variant-numeric:tabular-nums}.dsm-tab[aria-selected=true]{color:var(--dsw-alias-label-primary,#17181a)}.dsm-tab[aria-selected=true]:after{background:var(--dsw-alias-brand-primary,#4d6bfe)}.dsm-tab[aria-selected=true] b{background:color-mix(in srgb,var(--dsw-alias-brand-primary,#4d6bfe) 12%,transparent);color:var(--dsw-alias-brand-primary,#4d6bfe)}
.dsm-toolbar{display:flex;align-items:center;gap:7px;min-height:52px;padding:8px 16px;border-bottom:1px solid var(--dsw-alias-border-l2,rgba(0,0,0,.1));background:var(--dsw-alias-bg-base,#fff)}.dsm-toolbar-actions{display:flex;gap:7px;align-items:center}.dsm-toolbar-spacer{flex:1}.dsm-selection{margin-right:2px;color:var(--dsw-alias-label-tertiary,#73777f);font-size:12px;font-variant-numeric:tabular-nums}.dsm-selection strong{color:var(--dsw-alias-label-primary,#17181a);font-size:13px}.dsm-danger-button{color:var(--dsw-alias-state-error-primary,#d93036)!important;border-color:color-mix(in srgb,var(--dsw-alias-state-error-primary,#d93036) 46%,transparent)!important}.dsm-danger-fill{background:var(--dsw-alias-state-error-primary,#d93036)!important;border-color:var(--dsw-alias-state-error-primary,#d93036)!important;color:var(--dsw-alias-label-primary-foreground,#fff)!important}
.dsm-main{position:relative;display:grid;grid-template-columns:minmax(460px,1fr) 342px;min-height:0;flex:1;background:var(--dsw-alias-bg-base,#fff)}.dsm-list{min-height:0;overflow:auto;padding:14px 14px 24px}.dsm-detail{min-height:0;overflow:auto;border-left:1px solid var(--dsw-alias-border-l2,rgba(0,0,0,.1));background:var(--dsw-alias-bg-layer-1,rgba(0,0,0,.018));padding:0}.dsm-state{display:flex;min-height:300px;flex-direction:column;align-items:center;justify-content:center;gap:7px;padding:28px;text-align:center;color:var(--dsw-alias-label-tertiary,#73777f);font-size:12px}.dsm-state strong{color:var(--dsw-alias-label-primary,#17181a);font-size:14px}
.dsm-group{margin-bottom:10px;overflow:hidden;border:1px solid var(--dsw-alias-border-l2,rgba(0,0,0,.1));border-radius:12px;background:var(--dsw-alias-bg-base,#fff)}.dsm-group-head{display:flex;align-items:center;gap:8px;min-height:50px;padding:6px 9px 6px 12px;background:var(--dsw-alias-bg-layer-1,rgba(0,0,0,.025))}.dsm-group-toggle{display:flex;align-items:center;gap:7px;min-width:0;flex:1;border:0;background:transparent;color:inherit;padding:2px;text-align:left;cursor:pointer}.dsm-group-toggle>svg{flex:none;color:var(--dsw-alias-label-tertiary,#73777f)}.dsm-group-title{display:block;min-width:0;flex:1}.dsm-group-name{display:block;font-size:13px;line-height:18px;font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dsm-group-path{display:block;margin-top:1px;color:var(--dsw-alias-label-tertiary,#73777f);font:10.5px/15px var(--ds-font-family-code,monospace);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dsm-group-count{flex:none;padding:3px 7px;border-radius:7px;background:var(--dsw-alias-bg-base,#fff);color:var(--dsw-alias-label-secondary,#565a61);font-size:11px;font-weight:600;font-variant-numeric:tabular-nums}.dsm-group-selected{flex:none;color:var(--dsw-alias-brand-primary,#4d6bfe);font-size:11px;font-weight:600;font-variant-numeric:tabular-nums}.dsm-group-rows{border-top:1px solid var(--dsw-alias-border-l2,rgba(0,0,0,.08))}.dsm-group-empty{padding:16px;color:var(--dsw-alias-label-tertiary,#73777f);font-size:12px;text-align:center}
.dsm-check-cell,.dsm-group-check-cell{display:grid;place-items:center;width:44px;height:44px;flex:none}.dsm-check{width:19px;height:19px;margin:0;accent-color:var(--dsw-alias-brand-primary,#4d6bfe);cursor:pointer}.dsm-check:disabled{cursor:not-allowed}
.dsm-row{position:relative;display:grid;grid-template-columns:44px minmax(150px,1fr) 128px auto;align-items:center;gap:9px;min-height:58px;padding:6px 9px 6px 2px;border-top:1px solid var(--dsw-alias-border-l2,rgba(0,0,0,.075));background:transparent;color:inherit;cursor:pointer}.dsm-row:first-child{border-top:0}.dsm-row:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(0,0,0,.045))}.dsm-row[data-current=true]{box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--dsw-alias-brand-primary,#4d6bfe) 44%,transparent)}.dsm-row[data-selected=true]{background:color-mix(in srgb,var(--dsw-alias-brand-primary,#4d6bfe) 8%,transparent);box-shadow:inset 3px 0 0 var(--dsw-alias-brand-primary,#4d6bfe)}.dsm-row[data-selected=true][data-current=true]{box-shadow:inset 3px 0 0 var(--dsw-alias-brand-primary,#4d6bfe),inset 0 0 0 1px color-mix(in srgb,var(--dsw-alias-brand-primary,#4d6bfe) 44%,transparent)}.dsm-row-identity{display:block;min-width:0}.dsm-row-title{display:block;font-size:13px;line-height:18px;font-weight:620;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dsm-row-meta{display:flex;align-items:center;gap:9px;margin-top:2px;color:var(--dsw-alias-label-tertiary,#73777f);font-size:10.5px;line-height:16px;white-space:nowrap;overflow:hidden}.dsm-row-meta>span{display:inline-flex;align-items:center;gap:5px;min-width:0;overflow:hidden;text-overflow:ellipsis}.dsm-row-context{display:grid;grid-template-columns:1fr auto;gap:2px 7px;align-items:center;color:var(--dsw-alias-label-secondary,#565a61);font-variant-numeric:tabular-nums}.dsm-row-context-label{font-size:11px;font-weight:620}.dsm-row-context small{grid-column:1/-1;color:var(--dsw-alias-label-tertiary,#73777f);font-size:9.5px;text-align:right}.dsm-mini-progress{display:block;width:38px;height:4px;border-radius:999px;background:var(--dsw-alias-border-l2,rgba(0,0,0,.12));overflow:hidden}.dsm-mini-progress i{display:block;height:100%;border-radius:inherit;background:var(--dsw-alias-brand-primary,#4d6bfe)}.dsm-row-context[data-level=warning] .dsm-row-context-label{color:var(--dsw-alias-state-warn-primary,#b86b00)}.dsm-row-context[data-level=warning] .dsm-mini-progress i{background:var(--dsw-alias-state-warn-primary,#b86b00)}.dsm-row-context[data-level=danger] .dsm-row-context-label{color:var(--dsw-alias-state-error-primary,#d93036)}.dsm-row-context[data-level=danger] .dsm-mini-progress i{background:var(--dsw-alias-state-error-primary,#d93036)}.dsm-row-actions{display:flex;align-items:center;justify-content:flex-end;gap:3px;white-space:nowrap}
.dsm-detail-empty{height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:7px;padding:28px;color:var(--dsw-alias-label-tertiary,#73777f);font-size:12px;text-align:center}.dsm-detail-empty svg{margin-bottom:3px;color:var(--dsw-alias-brand-primary,#4d6bfe)}.dsm-detail-empty strong{color:var(--dsw-alias-label-primary,#17181a);font-size:14px}.dsm-detail-content{padding:18px}.dsm-detail-head{display:flex;align-items:flex-start;gap:8px}.dsm-detail-heading{min-width:0;flex:1}.dsm-detail-kicker,.dsm-detail-close-label{display:none}.dsm-detail h3{margin:0;font-size:16px;line-height:23px;font-weight:670;word-break:break-word}.dsm-status-line{display:flex;align-items:center;gap:6px;margin-top:3px;color:var(--dsw-alias-label-secondary,#565a61);font-size:11px}.dsm-detail-close{flex:none}.dsm-detail-restore{margin-top:12px}.dsm-mono{margin-top:5px;font:10.5px/16px var(--ds-font-family-code,monospace);word-break:break-all;color:var(--dsw-alias-label-tertiary,#73777f)}
.dsm-context-card{margin-top:16px;padding:12px;border:1px solid var(--dsw-alias-border-l2,rgba(0,0,0,.1));border-radius:10px;background:var(--dsw-alias-bg-base,#fff)}.dsm-context-card-head{display:flex;align-items:baseline;justify-content:space-between;color:var(--dsw-alias-label-secondary,#565a61);font-size:11px}.dsm-context-card-head strong{color:var(--dsw-alias-brand-primary,#4d6bfe);font-size:20px;line-height:24px;font-variant-numeric:tabular-nums}.dsm-progress{height:7px;margin:8px 0 6px;border-radius:999px;background:var(--dsw-alias-border-l2,rgba(0,0,0,.12));overflow:hidden}.dsm-progress>span{display:block;height:100%;border-radius:inherit;background:var(--dsw-alias-brand-primary,#4d6bfe)}.dsm-context-card[data-level=warning] strong{color:var(--dsw-alias-state-warn-primary,#b86b00)}.dsm-context-card[data-level=warning] .dsm-progress>span{background:var(--dsw-alias-state-warn-primary,#b86b00)}.dsm-context-card[data-level=danger] strong{color:var(--dsw-alias-state-error-primary,#d93036)}.dsm-context-card[data-level=danger] .dsm-progress>span{background:var(--dsw-alias-state-error-primary,#d93036)}.dsm-context-values{color:var(--dsw-alias-label-tertiary,#73777f);font-size:10.5px;font-variant-numeric:tabular-nums}
.dsm-detail-section{margin-top:20px}.dsm-detail-section h4{margin:0 0 9px;color:var(--dsw-alias-label-secondary,#565a61);font-size:11px;line-height:16px;font-weight:700;letter-spacing:.045em}.dsm-facts{display:grid;grid-template-columns:104px minmax(0,1fr);gap:7px 10px;margin:0}.dsm-facts dt{color:var(--dsw-alias-label-tertiary,#73777f);font-size:11px;line-height:17px}.dsm-facts dd{margin:0;color:var(--dsw-alias-label-primary,#17181a);font-size:11px;line-height:17px;text-align:left;word-break:break-word;font-variant-numeric:tabular-nums}.dsm-facts .dsm-mono-value{font-family:var(--ds-font-family-code,monospace);font-size:10.5px}
.dsm-feedback{padding:10px 12px;border-radius:10px;background:var(--dsw-alias-bg-layer-1,rgba(0,0,0,.04));font-size:12px;line-height:18px}.dsm-window-feedback{margin:8px 16px 0}.dsm-feedback[data-kind=error]{color:var(--dsw-alias-state-error-primary,#d93036);background:color-mix(in srgb,var(--dsw-alias-state-error-primary,#d93036) 9%,transparent)}.dsm-blockers{margin:8px 0 0;padding-left:18px}.dsm-blockers code{font-size:11px}
.dsm-confirm-icon{display:grid;place-items:center;width:42px;height:42px;border-radius:12px;color:var(--dsw-alias-state-error-primary,#d93036);background:color-mix(in srgb,var(--dsw-alias-state-error-primary,#d93036) 10%,transparent)}.dsm-confirm h2{margin:0;font-size:18px;line-height:25px}.dsm-confirm p{margin:0;color:var(--dsw-alias-label-secondary,#565a61);font-size:13px;line-height:20px}.dsm-confirm-ids{max-height:120px;overflow:auto;padding:9px 11px;border:1px solid var(--dsw-alias-border-l2,rgba(0,0,0,.09));border-radius:9px;background:var(--dsw-alias-bg-layer-1,rgba(0,0,0,.03));font:10.5px/17px var(--ds-font-family-code,monospace);word-break:break-all}.dsm-ack{display:flex;gap:10px;align-items:flex-start;font-size:13px;line-height:20px}.dsm-ack input{width:18px;height:18px;margin-top:1px;accent-color:var(--dsw-alias-state-error-primary,#d93036)}.dsm-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:2px}
.dsm-footer{display:flex;align-items:center;justify-content:space-between;min-height:32px;padding:0 16px;border-top:1px solid var(--dsw-alias-border-l2,rgba(0,0,0,.1));color:var(--dsw-alias-label-tertiary,#73777f);font-size:10.5px;font-variant-numeric:tabular-nums}.dsm-footer>span{display:inline-flex;align-items:center;gap:6px}.dsm-spinner{animation:dsm-spin .8s linear infinite}@keyframes dsm-spin{to{transform:rotate(360deg)}}
@media(max-width:900px){.dsm-main{grid-template-columns:minmax(400px,1fr) 300px}.dsm-row{grid-template-columns:44px minmax(120px,1fr) 90px auto}.dsm-row-context small{display:none}.dsm-group-selected{display:none}}
@media(max-width:720px){.dsm-overlay{padding:6px}.dsm-window{width:calc(100vw - 12px);height:calc(100vh - 12px);border-radius:13px}.dsm-head{padding:0 12px}.dsm-head-mark{display:none}.dsm-tabs{padding:0 14px;gap:14px}.dsm-tab{gap:5px}.dsm-tab b{padding:0 5px;font-size:10px}.dsm-toolbar{flex-wrap:wrap;padding:8px 10px}.dsm-toolbar button{min-height:44px}.dsm-toolbar-spacer{display:none}.dsm-selection{order:-1;width:100%}.dsm-main{grid-template-columns:1fr;overflow:hidden}.dsm-list{padding:10px}.dsm-detail{display:block;position:absolute;inset:0;z-index:2;border:0;background:var(--dsw-alias-bg-base,#fff);transform:translateX(100%);visibility:hidden;transition:transform .18s ease,visibility 0s linear .18s}.dsm-detail[data-open=true]{transform:translateX(0);visibility:visible;transition-delay:0s}.dsm-detail-kicker{display:block;margin-bottom:3px;color:var(--dsw-alias-label-tertiary,#73777f);font-size:11px;font-weight:650;letter-spacing:.04em}.dsm-detail-close{display:inline-flex!important;align-items:center;gap:4px}.dsm-detail-close-label{display:inline}.dsm-row{grid-template-columns:44px minmax(96px,1fr) 78px 44px;gap:6px;padding-left:2px}.dsm-row-meta>span:last-child{display:block;overflow:hidden;text-overflow:ellipsis}.dsm-row-context{display:block;min-width:0;text-align:right}.dsm-row-context-label{display:block;white-space:nowrap}.dsm-row-context small,.dsm-mini-progress,.dsm-row-actions button:first-child:not(:last-child){display:none}.dsm-row-actions button{min-width:44px;min-height:44px;font-size:0}.dsm-row-actions button svg{margin:0}.dsm-group-path,.dsm-group-selected,.dsm-group-head>button:not(.dsm-group-toggle){display:none}.dsm-group-toggle,.dsm-tab,.dsm-icon-btn,.dsm-detail button{min-width:44px;min-height:44px}.dsm-footer{padding:0 10px}}
@media(prefers-reduced-motion:reduce){.dsm-spinner{animation:none}.dsm-detail{transition:none}}
.dsm-footer-btn{display:inline-grid;place-items:center;width:30px;height:30px;border:0;border-radius:8px;background:transparent;color:var(--dsw-alias-label-secondary,#565a61);cursor:pointer}.dsm-footer-btn:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(0,0,0,.06));color:var(--dsw-alias-label-primary,#17181a)}.dsm-footer-btn:focus-visible{outline:2px solid var(--dsw-alias-brand-primary,#4d6bfe);outline-offset:2px}
.dsm-header-btn{display:inline-grid;place-items:center;width:28px;height:28px;border:0;border-radius:8px;background:transparent;color:var(--dsw-alias-label-secondary,#565a61);cursor:pointer}.dsm-header-btn:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(0,0,0,.06));color:var(--dsw-alias-state-error-primary,#d93036)}.dsm-header-btn:focus-visible{outline:2px solid var(--dsw-alias-brand-primary,#4d6bfe);outline-offset:2px}

/* 强停会话分段组：一个容器两个分区（⟳ 复活蓝 / ⏻ 离线红），危险描边淡染，贴合删除按钮占位 */
.dsm-force-group{display:inline-flex;align-items:center;height:28px;border:1px solid color-mix(in srgb,var(--dsw-alias-state-error-primary,#d93036) 26%,transparent);border-radius:8px;overflow:hidden}
.dsm-force-seg{display:grid;place-items:center;width:27px;height:26px;border:0;background:transparent;color:var(--dsw-alias-label-secondary,#565a61);cursor:pointer;transition:color .15s ease,background .15s ease,transform .12s ease}
.dsm-force-seg:active{transform:scale(.88)}
.dsm-force-seg svg{width:16px;height:16px}
.dsm-force-seg-resume:hover{color:var(--dsw-alias-brand-primary,#4d6bfe);background:color-mix(in srgb,var(--dsw-alias-brand-primary,#4d6bfe) 10%,transparent)}
.dsm-force-seg-offline:hover{color:var(--dsw-alias-state-error-primary,#d93036);background:color-mix(in srgb,var(--dsw-alias-state-error-primary,#d93036) 10%,transparent)}
.dsm-force-seg:focus-visible{outline:2px solid var(--dsw-alias-brand-primary,#4d6bfe);outline-offset:-2px}
.dsm-force-divider{width:1px;height:14px;background:var(--dsw-alias-border-l2,rgba(0,0,0,.14))}
@media(prefers-reduced-motion:reduce){.dsm-force-seg{transition:none}}
.dsm-force-outcome{display:grid;gap:7px;margin:2px 0 0;padding:11px 13px;border-radius:10px;background:var(--dsw-alias-bg-layer-1,rgba(0,0,0,.04));font-size:12px;line-height:19px}.dsm-force-outcome b{font-variant-numeric:tabular-nums}.dsm-force-outcome code{font-size:11px;color:var(--dsw-alias-label-tertiary,#73777f)}

/* 会话管理入口：工作区 section header 内、官方 header 按钮类克隆 */
.dsm-mgr-btn svg{width:16px;height:16px}

/* 工作区行「复制路径」按钮：附加在官方 rowActions 尾部、CSS order:-1 视觉置左（紧贴 ⋯），样式类克隆自官方按钮 */
.dsm-copy-btn{order:-1;position:relative;transition:transform .12s ease,color .15s ease,background .15s ease}
.dsm-copy-btn:hover{color:var(--dsw-alias-label-primary,#17181a)}
.dsm-copy-btn:active{transform:scale(.88)}
.dsm-copy-btn:focus-visible{outline:2px solid var(--dsw-alias-brand-primary,#4d6bfe);outline-offset:2px}
.dsm-copy-btn svg{width:15px;height:15px;transition:opacity .16s ease,transform .16s ease}
.dsm-copy-btn .dsm-copy-check{position:absolute;inset:0;opacity:0;transform:scale(.55);color:var(--dsw-alias-state-success-primary,#2e9e5b)}
.dsm-copy-btn.dsm-copied .dsm-copy-ico{opacity:0;transform:scale(.55)}
.dsm-copy-btn.dsm-copied .dsm-copy-check{opacity:1;transform:scale(1)}
.dsm-copy-toast{position:fixed;left:50%;bottom:26px;z-index:1600;transform:translateX(-50%);max-width:min(560px,86vw);padding:9px 14px;border-radius:10px;background:var(--dsw-alias-bg-tooltip,#26282d);color:var(--dsw-alias-label-primary-foreground,#fff);font-family:var(--dsw-font-family,Inter,system-ui,sans-serif);font-size:12px;line-height:18px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;box-shadow:0 10px 34px rgba(0,0,0,.28);animation:dsm-copy-toast-in .18s ease;transition:opacity .24s ease}
.dsm-copy-toast--error{background:var(--dsw-alias-state-error-primary,#d93036)}
@keyframes dsm-copy-toast-in{from{opacity:0;transform:translate(-50%,8px)}to{opacity:1;transform:translate(-50%,0)}}
@media(prefers-reduced-motion:reduce){.dsm-copy-btn,.dsm-copy-btn svg{transition:none}.dsm-copy-toast{animation:none}}
`

